name: SampleCon
permalink: /:categories/:title
exclude:
  - questions.txt
  - config.ru
  - Procfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - gems
  - unicorn.rb
  - /_posts/team
  - /_posts/careers
assets:
  compress:
    css: sass
    js: uglifier
twitter_url: http://twitter.com/fedsample/   
register_url: http://samplecon.brownpapertickets.com/ 