name: SampleCon
permalink: /:categories/:title
exclude:
  - questions.txt
  - config.ru
  - Procfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - gems
  - unicorn.rb
  - /_posts/team
  - /_posts/careers
assets:
  compress:
    css: sass
    js: uglifier
twitter_url: http://twitter.com/fedsample/
register_url: http://samplecon.brownpapertickets.com/

attendees:
  - ["Chris Andaya", "Vision Critical", "Toronto, ON"]
  - ["Carrie Angiolet", "Illuminas", "Austin, TX"]
  - ["Brook Baston", "MyPoints.com", "San Francisco, CA"]
  - ["Taylor Beery", "Crescent Sample", "New Orleans, LA"]
  - ["Rob Berger", "Vision Critical", "Toronto, ON"]
  - ["Mike Billingsley", "Research Now", "Plano, TX"]
  - ["Peter Bodenheimer", "Flatstack", "New Orleans, LA"]
  - ["Dyna Boen", "Federated Sample", "San Francisco, CA"]
  - ["Yaron Brenman", "Ugam Solutions", "New York, NY"]
  - ["Bonnie Breslauer", "Lightspeed Research", "Warren, NJ"]
  - ["Janna de Bruijne", "Points2Shop", "Alpharetta, GA"]
  - ["Amelia Carry", "Illuminas", "Austin, TX"]
  - ["Patrick Comer", "Federated Sample", "New Orleans, LA"]
  - ["Jose Correa", "MarketView Research", "Edgewater, NJ"]
  - ["Mitchell Dagley", "The Link Group", "Atlanta, GA"]
  - ["Jonathan Deitch", "Ipsos", "Columbia, MD"]
  - ["Tony Dent", "Sample Answers", "Surrey, UK"]
  - ["Joe Detuno", "Prodégé", "Los Angeles, CA"]
  - ["Matt Dohm", "Lightspeed Research", "Seattle, WA"]
  - ["Andy Ellis", "Federated Sample", "Denver, CO"]
  - ["Jeremy Engelin", "Phoenix Marketing International ", "Rhinebeck, NY"]
  - ["Chris Fabber", "GfK", "New York, NY"]
  - ["Gene Filipi", "Kinesis Survey Technologies", "San Francisco, CA"]
  - ["Dan Fitzgerald", "GMI", "New York, NY"]
  - ["Clif Fleitas", "uSamp", "Los Angeles, CA"]
  - ["Brad Franz", "Burke, Inc.", "Cincinnati, OH"]
  - ["Calvin Friesth", "Prodégé", "Los Angeles, CA"]
  - ["Jeff Gerken", "Research Panel Asia", "New York, NY"]
  - ["Garrett Gil de Rubio", "Points2Shop", "Alpharetta, GA"]
  - ["Don Golden", "Precision Sample", "Denver, CO"]
  - ["Bert Goyne", "Askia", "San Francisco, CA"]
  - ["Michael Holmes", "EMI Research Solutions", "Cincinatti, OH"]
  - ["Steve Hopkins", "Market Cube", "McLean, VA"]
  - ["Rachel Jenkins", "Precision Sample", "Denver, CO"]
  - ["Mathijs de Jong", "Points2Shop", "Alpharetta, GA"]
  - ["Corey Julseth", "Harris Interactive Service Bureau", "Rochester, NY"]
  - ["Tony Kretzmer", "ISA", "Van Nuys, CA"]
  - ["Julian Lewis", "Clear Voice Research", "Denver, CO"]
  - ["Jim Longo", "Discuss.IO", "New Orleans, LA"]
  - ["Lev Mazin", "AYTM.com", "San Francisco, CA"]
  - ["Lesley McCormick", "Clear Voice Research", "Denver, CO"]
  - ["Michael McCrary", "Federated Sample", "New Orleans, LA"]
  - ["James McNamara", "Penn Schoen Berland", "Washington D.C."]
  - ["Mark Menig", "TrueSample", "Seattle, WA"]
  - ["Jessica Metcalf", "The Link Group", "Atlanta, GA"]
  - ["Peter Milla", "Cint", "Centerport, NY"]
  - ["Chuck Miller", "Digital Marketing & Measurement, LLC", "Dallas, TX"]
  - ["Madhav Mirani", "Ugam Solutions", "New York, NY"]
  - ["Tariq Mirza", "Kinesis Survey Technologies", "London, UK"]
  - ["Mike Misel", "Harris Interactive Service Bureau", "Los Angeles, CA"]
  - ["Brin Moore", "MyPoints.com", "San Francisco, CA"]
  - ["Mendy Orimland", "Prodégé", "Los Angeles, CA"]
  - ["Jayme Plunkett", "Decipher", "Fresno, CA"]
  - ["Edan Portaro", "uSamp", "Los Angeles, CA"]
  - ["Cliff Przybyl", "Market Cube", "McLean, VA"]
  - ["Jacqueline Rosales", "SoapBoxSample", "Van Nuys, CA"]
  - ["Glen Saunders", "WebMD", "New York, NY"]
  - ["Brett Schnittlich", "Federated Sample", "New Orleans, LA"]
  - ["Chris Schultz", "Flatstack", "New Orleans, LA"]
  - ["Nicole Schumann", "Prodégé", "Los Angeles, CA"]
  - ["John Sessions", "Bellomy Research", "Winstom-Salem, NC"]
  - ["Kristine Sinisi", "Lightspeed Research", "Warren, NJ"]
  - ["Jason Thomas", "Decision Analyst", "Arlington, TX"]
  - ["Leslie Townsend", "Kinesis Survey Technologies", "Austin, TX"]
  - ["Lori Tripphahn", "Harris Interactive Service Bureau", "Rochester, NY"]
  - ["Aaron Walton", "EMI Research Solutions", "Cincinatti, OH"]
  - ["Leah Wang", "WebMD", "New York, NY"]
  - ["Mauricia Wills", "Decision Analyst", "Arlington, TX"]
  - ["Jake Wolff", "Cint", "Princeton, NJ"]
  - ["Danny Wong", "CfMC", "San Francisco, CA"]
