name: SampleCon
permalink: /:categories/:title
exclude:
  - questions.txt
  - config.ru
  - Procfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - gems
  - unicorn.rb
  - /_posts/team
  - /_posts/careers
assets:
  compress:
    css: sass
    js: uglifier
twitter_url: http://twitter.com/fedsample/   
register_url: http://samplecon.brownpapertickets.com/

attendees:
  - ["Chris Andaya", "Vision Critical", "Toronto, ON"]
  - ["Carrie Angiolet", "Illuminas", "Austin, TX"]
  - ["Taylor Beery", "Crescent Sample", "New Orleans, LA"]
  - ["Rob Berger", "Vision Critical", "Toronto", " ON"]
  - ["Michael Billingsley", "Research Now", "Plano, TX"]
  - ["Yaron Brenman", "UGAM Solutions", "New York, NY"]
  - ["Bonnie Breslaur", "Lightspeed Research", "Warren, NJ"]
  - ["Jannade Bruijne", "Points2Shop", "Alpharetta, GA"]
  - ["Ameila Carry", "Illuminas", "Austin, TX"]
  - ["Patrick Comer", "Federated Sample", "New Orleans, LA"]
  - ["Jose Correa", "Marketview Research", "Edgewater, NJ"]
  - ["Mitchell Dagley", "The Link Group", "Atlanta, GA"]
  - ["Tony Dent", "Sample Answers", "Surrey, UK"]
  - ["Joe Detuno", "Prodege", "Los Angeles, CA"]
  - ["Andy Ellis", "Federated Sample", "Denver, CO"]
  - ["Jeremy Engelin", "Phoenix Marketing International ", "Rhinebeck, NY"]
  - ["Chris Fabber", "GfK", "New York, NY"]
  - ["Dan Fitzgerald", "GMI", "New York, NY"]
  - ["Calvin Friesth", "Prodege", "Los Angeles, CA"]
  - ["Jeff Gerken", "Research Panel Asia", "New York, NY"]
  - ["Garrett Gil de Rubio", "Points2Shop", "Alpharetta, GA"]
  - ["Don Golden", "Precision Sample", "Denver, CO"]
  - ["Michael Holmes", "EMI Research Solutions", "Cincinatti, OH"]
  - ["Steve Hopkins", "MarketCube", "McLean, VA"]
  - ["Rachel Jenkins", "Precision Sample", "Denver, CO"]
  - ["Mathijs de Jong", "Points2Shop", "Alpharetta, GA"]
  - ["Corey Julseth", "Harris Interactive", "Rochester, NY"]
  - ["Joe Kleine", "WebMD", "New York, NY"]
  - ["Tony Kretzmer", "ISA", "Van Nuys, CA"]
  - ["Lev Mazin", "AYTM", "San Francisco, CA"]
  - ["Michael McCrary", "Federated Sample", "New Orleans, LA"]
  - ["Jessica Metcalf", "The Link Group", "Atlanta, GA"]
  - ["Peter Milla", "Cint", "Centerport, NY"]
  - ["Chuck Miller", "Digital Marketing & Measurement, LLC", "Dallas, TX"]
  - ["Madhav Mirani", "UGAM Solutions", "New York, NY"]
  - ["Mike Misel", "Harris Interactive", "Los Angeles, CA"]
  - ["Mendy Orimland", "Prodege", "Los Angeles, CA"]
  - ["Jayme Plunkett", "Decipher", "Fresno, CA"]
  - ["Cliff Przybyl", "MarketCube", "McLean, VA"]
  - ["Jacqueline Rosales", "SoapBoxSample", "Van Nuys, CA"]
  - ["Brett Schnittlich", "Federated Sample", "New Orleans, LA"]
  - ["Chris Schultz", "Flatstack", "New Orleans, LA"]
  - ["Nicole Schumann", "Prodege", "Los Angeles, CA"]
  - ["Kristine Sinisi", "Lightspeed Research", "Warren, NJ"]
  - ["Jason Thomas", "Decision Analyst", "Arlington, TX"]
  - ["Lori Tripphahn", "Harris Interactive", "Rochester, NY"]
  - ["Aaron Walton", "EMI Research Solutions", "Cincinatti, OH"]
  - ["Leah Wang", "WebMD", "New York, NY"]
  - ["Mauricia Wills", "Decision Analyst", "Arlington, TX"]
  - ["Jake Wolff", "Cint", "Princeton, NJ"]
  - ["Danny Wong", "CfMC", "San Francisco, CA"]